services:
  - type: web
    name: churn-prediction-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run webapp/app.py --server.port 10000 --server.address 0.0.0.0"
    plan: free